blank_issues_enabled: false
contact_links:
  - name: DeepWeb Documentation
    url: https://github.com/yourusername/deepweb/wiki
    about: Please check our documentation for answers to common questions
  - name: Community Discussions
    url: https://github.com/yourusername/deepweb/discussions
    about: Ask questions and discuss with the community
  - name: Security Issues
    url: mailto:security@deepwebai.com
    about: Please report security vulnerabilities privately via email